# Pre-build step: minify + gzip every .html under src/, emit <Name>Html.generated.h
# with a PROGMEM byte array that WebUi serves gzip-compressed.
# Same approach as crosspoint-reader's scripts/build_html.py.
# (Don't mention the HTTP header name in the first two lines: Python would
# parse "...ncoding: gzip" as a source encoding declaration.)

import gzip
import os
import re

SRC_DIR = "src"


def minify_html(html: str) -> str:
    preserve_tags = ["pre", "code", "textarea", "script", "style"]
    preserve_regex = "|".join(preserve_tags)

    preserve_blocks = []

    def preserve(match):
        preserve_blocks.append(match.group(0))
        return f"__PRESERVE_BLOCK_{len(preserve_blocks)-1}__"

    html = re.sub(rf"<({preserve_regex})[\s\S]*?</\1>", preserve, html, flags=re.IGNORECASE)
    html = re.sub(r"<!--.*?-->", "", html, flags=re.DOTALL)
    html = re.sub(r">\s+<", "><", html)
    html = re.sub(r"\s+", " ", html)

    for i, block in enumerate(preserve_blocks):
        html = html.replace(f"__PRESERVE_BLOCK_{i}__", block)

    return html.strip()


def sanitize_identifier(name: str) -> str:
    sanitized = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    if sanitized and sanitized[0].isdigit():
        sanitized = f"_{sanitized}"
    return sanitized


for root, _, files in os.walk(SRC_DIR):
    for file in files:
        if not file.endswith(".html"):
            continue
        file_path = os.path.join(root, file)
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()

        processed = minify_html(content)
        compressed = gzip.compress(processed.encode("utf-8"), compresslevel=9)

        base_name = sanitize_identifier(f"{os.path.splitext(file)[0]}Html")
        header_path = os.path.join(root, f"{base_name}.generated.h")

        with open(header_path, "w", encoding="utf-8") as h:
            h.write("// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY\n\n")
            h.write("#pragma once\n")
            h.write("#include <Arduino.h>\n")
            h.write("#include <cstddef>\n\n")
            h.write(f"constexpr char {base_name}[] PROGMEM = {{\n")
            for i in range(0, len(compressed), 16):
                chunk = compressed[i : i + 16]
                hex_values = ", ".join(f"0x{b:02x}" for b in chunk)
                h.write(f"  {hex_values},\n")
            h.write("};\n\n")
            h.write(f"constexpr size_t {base_name}CompressedSize = {len(compressed)};\n")

        print(f"Generated: {header_path} ({len(content)} -> {len(compressed)} bytes)")
