# Pre-build step: embed binary assets (the default alarm WAV) as PROGMEM
# arrays. assets/sounds/default_alarm.wav -> src/audio/DefaultAlarmWav.generated.h

import os

# Runs under SCons (no __file__); the cwd is the project root.
ROOT = os.getcwd()

ASSETS = [
    (
        os.path.join(ROOT, "assets", "sounds", "default_alarm.wav"),
        os.path.join(ROOT, "src", "audio", "DefaultAlarmWav.generated.h"),
        "DefaultAlarmWav",
    ),
]

for src, dst, name in ASSETS:
    with open(src, "rb") as f:
        data = f.read()
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    with open(dst, "w") as h:
        h.write("// THIS FILE IS AUTOGENERATED by scripts/embed_assets.py, DO NOT EDIT\n\n")
        h.write("#pragma once\n#include <Arduino.h>\n#include <cstddef>\n\n")
        h.write(f"constexpr uint8_t {name}[] PROGMEM = {{\n")
        for i in range(0, len(data), 16):
            chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + 16])
            h.write(f"  {chunk},\n")
        h.write("};\n\n")
        h.write(f"constexpr size_t {name}Size = {len(data)};\n")
    print(f"Embedded: {src} -> {dst} ({len(data)} bytes)")
