#!/usr/bin/env python3
"""Rasterize Noto Sans (SIL OFL) into 1-bit C font tables for GfxText.

Output format is GfxText's own FontDef/GlyphDef structs (see lib/GfxText/GfxText.h):
per-glyph bit-packed bitmaps (MSB = leftmost pixel), ASCII 0x20-0x7E.

Usage: python3 scripts/gen_fonts.py <NotoSans-Regular.ttf> <NotoSans-Bold.ttf>
Writes headers into lib/GfxText/fonts/. The headers are checked in; rerun only
to change sizes or the typeface.
"""

import os
import sys

from PIL import Image, ImageDraw, ImageFont

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "lib", "GfxText", "fonts")
FIRST, LAST = 0x20, 0x7E

# (name, ttf_index, pixel_size) — ttf_index: 0=regular, 1=bold
# Sized for the Murphy M3's 3.7" 416x240 panel (~130 DPI).
FONTS = [
    ("NotoSans10", 0, 10),
    ("NotoSans12", 0, 12),
    ("NotoSans12B", 1, 12),
    ("NotoSans15", 0, 15),
    ("NotoSans15B", 1, 15),
    ("NotoSans21B", 1, 21),
    ("NotoSans28B", 1, 28),
]

THRESHOLD = 128
CANVAS = 256
PAD = 64


def build_font(name, ttf_path, px):
    font = ImageFont.truetype(ttf_path, px)
    ascent, descent = font.getmetrics()

    bitmap_bytes = bytearray()
    glyphs = []

    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        img = Image.new("L", (CANVAS, CANVAS), 0)
        draw = ImageDraw.Draw(img)
        draw.text((PAD, PAD), ch, font=font, fill=255, anchor="ls")  # baseline at (PAD, PAD)

        advance = max(0, round(font.getlength(ch)))
        bbox = img.point(lambda v: 255 if v >= THRESHOLD else 0).getbbox()
        if bbox is None:  # space etc.
            glyphs.append((len(bitmap_bytes), 0, 0, advance, 0, 0))
            continue

        x0, y0, x1, y1 = bbox
        w, h = x1 - x0, y1 - y0
        x_off = x0 - PAD
        y_off = y0 - PAD  # negative above baseline

        offset = len(bitmap_bytes)
        bits = []
        px_data = img.load()
        for yy in range(y0, y1):
            for xx in range(x0, x1):
                bits.append(1 if px_data[xx, yy] >= THRESHOLD else 0)
        # pack MSB-first
        for i in range(0, len(bits), 8):
            byte = 0
            for j, b in enumerate(bits[i : i + 8]):
                byte |= b << (7 - j)
            bitmap_bytes.append(byte)

        glyphs.append((offset, w, h, advance, x_off, y_off))

    y_advance = ascent + descent
    return bitmap_bytes, glyphs, ascent, y_advance


def emit_header(name, bitmap_bytes, glyphs, ascent, y_advance):
    path = os.path.join(OUT_DIR, f"{name}.h")
    with open(path, "w") as f:
        f.write("// AUTOGENERATED by scripts/gen_fonts.py — do not edit.\n")
        f.write("// Typeface: Noto Sans (SIL Open Font License 1.1, see OFL.txt).\n\n")
        f.write("#pragma once\n#include \"../GfxText.h\"\n\n")
        f.write(f"static const uint8_t {name}Bitmaps[] = {{\n")
        for i in range(0, len(bitmap_bytes), 16):
            chunk = ", ".join(f"0x{b:02x}" for b in bitmap_bytes[i : i + 16])
            f.write(f"  {chunk},\n")
        f.write("};\n\n")
        f.write(f"static const GlyphDef {name}Glyphs[] = {{\n")
        for offset, w, h, adv, xo, yo in glyphs:
            f.write(f"  {{{offset}, {w}, {h}, {adv}, {xo}, {yo}}},\n")
        f.write("};\n\n")
        f.write(
            f"static const FontDef {name} = {{{name}Bitmaps, {name}Glyphs, "
            f"{FIRST}, {LAST}, {y_advance}, {ascent}}};\n"
        )
    size = len(bitmap_bytes) + len(glyphs) * 8
    print(f"{name}: {len(bitmap_bytes)} bitmap bytes, ~{size} bytes total")


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    ttfs = [sys.argv[1], sys.argv[2]]
    os.makedirs(OUT_DIR, exist_ok=True)
    for name, ttf_index, px in FONTS:
        bitmap_bytes, glyphs, ascent, y_advance = build_font(name, ttfs[ttf_index], px)
        emit_header(name, bitmap_bytes, glyphs, ascent, y_advance)


if __name__ == "__main__":
    main()
